"""
Synthetic price generator with *known ground truth*.

Everything here is generated by this file — no market data, ever. The point is that
we plant the structure ourselves, so any later claim ("the pipeline recovers the
signal", "random k-fold inflates AUC") can be checked against the truth we planted.

Switches (all off-able, so we can build a genuine null):
  * GBM baseline                                  -> always on
  * volatility clustering                         -> vol_model in {"none","markov","garch"}
  * planted latent drift state + noisy observation -> signal_prob, signal_drift, snr
  * intra-bar path at 1-minute resolution          -> minutes_per_day

The generator returns the *fine* path as an (n_bars, minutes_per_day + 1) matrix so
that path-dependent labeling (notebook 02) can look inside a bar instead of guessing
from OHLC.
"""
from __future__ import annotations

from dataclasses import dataclass, field, replace

import numpy as np
import pandas as pd

TRADING_DAYS = 252


# --------------------------------------------------------------------------------------
# configuration
# --------------------------------------------------------------------------------------
@dataclass(frozen=True)
class SimConfig:
    """Every structural property of the series is a parameter here."""

    # --- geometry -----------------------------------------------------------------
    n_bars: int = 1500                  # number of daily bars
    minutes_per_day: int = 390          # intra-bar resolution (0 => no fine path)
    s0: float = 100.0
    start: str = "2015-01-02"

    # --- GBM baseline (annualised) -------------------------------------------------
    mu: float = 0.05
    sigma: float = 0.20

    # --- volatility clustering -----------------------------------------------------
    vol_model: str = "markov"           # "none" | "markov" | "garch"
    vol_mult: tuple[float, float] = (0.7, 2.2)      # markov: vol multiplier per state
    p_stay: tuple[float, float] = (0.985, 0.960)    # markov: P(stay) in state 0 / 1
    normalise_vol: bool = True          # rescale so E[sigma^2] == sigma^2 in every vol_model
    garch: tuple[float, float] = (0.12, 0.85)       # (alpha, beta); omega set by sigma

    # --- planted signal ------------------------------------------------------------
    signal_prob: float = 0.02           # P(a new episode starts on an idle bar)
    signal_k: int = 10                  # episode length in bars
    signal_drift: float = 0.4           # extra drift per bar, in units of daily sigma
    signal_two_sided: bool = False      # if True episodes are up *or* down (sign in truth.z)
    snr: float = 1.0                    # amplitude of the state in the observed feature
    feat_noise_phi: float = 0.5         # AR(1) persistence of the feature's noise
    n_noise_features: int = 3           # extra pure-noise AR(1) features

    seed: int = 0

    def with_(self, **kw) -> "SimConfig":
        return replace(self, **kw)


def null_config(**kw) -> SimConfig:
    """A *genuine* null: no latent drift episodes and an uninformative feature.

    Note the distinction that matters later: `snr=0` alone only blinds the explicit
    feature — if `signal_prob>0` the price itself still trends during episodes, so
    price-derived features (momentum, vol) remain predictive. A true null needs
    `signal_prob=0` as well. This helper does both.
    """
    return SimConfig(signal_prob=0.0, signal_drift=0.0, snr=0.0).with_(**kw)


@dataclass
class SimData:
    cfg: SimConfig
    bars: pd.DataFrame                  # open/high/low/close/volume, indexed by bar date
    fine: np.ndarray                    # (n_bars, minutes_per_day+1) intra-bar prices
    fine_index: pd.DatetimeIndex        # flattened minute timestamps (n_bars*(M+1),)
    features: pd.DataFrame              # observable at each bar's close
    truth: pd.DataFrame                 # latent state / regime / sigma — validation only
    _fields: dict = field(default_factory=dict)

    @property
    def close(self) -> pd.Series:
        return self.bars["close"]

    def fine_path(self, i: int) -> np.ndarray:
        """Minute prices inside bar i (index 0 is the bar's open)."""
        return self.fine[i]


# --------------------------------------------------------------------------------------
# latent processes
# --------------------------------------------------------------------------------------
def _markov_regimes(n: int, p_stay: tuple[float, float], rng: np.random.Generator) -> np.ndarray:
    s = np.zeros(n, dtype=int)
    u = rng.random(n)
    for t in range(1, n):
        stay = u[t] < p_stay[s[t - 1]]
        s[t] = s[t - 1] if stay else 1 - s[t - 1]
    return s


def _signal_episodes(n: int, prob: float, k: int, rng: np.random.Generator,
                     two_sided: bool = False) -> np.ndarray:
    """z[t] = +/-1 while bar t sits inside an episode of shifted drift, else 0."""
    z = np.zeros(n, dtype=int)
    if prob <= 0 or k <= 0:
        return z
    u = rng.random(n)
    t = 0
    while t < n:
        if u[t] < prob:
            sign = rng.choice([-1, 1]) if two_sided else 1
            z[t: t + k] = sign
            t += k
        else:
            t += 1
    return z


def _ar1(n: int, phi: float, rng: np.random.Generator) -> np.ndarray:
    """Unit-variance AR(1) — persistence without changing the noise scale."""
    e = rng.standard_normal(n)
    if phi == 0:
        return e
    x = np.empty(n)
    x[0] = e[0]
    s = np.sqrt(1.0 - phi ** 2)
    for t in range(1, n):
        x[t] = phi * x[t - 1] + s * e[t]
    return x


# --------------------------------------------------------------------------------------
# main generator
# --------------------------------------------------------------------------------------
def simulate(cfg: SimConfig) -> SimData:
    rng = np.random.default_rng(cfg.seed)
    n, M = cfg.n_bars, cfg.minutes_per_day

    sig_d = cfg.sigma / np.sqrt(TRADING_DAYS)      # baseline daily vol
    mu_d = cfg.mu / TRADING_DAYS                   # baseline daily drift

    # --- latent drift state ---------------------------------------------------------
    z = _signal_episodes(n, cfg.signal_prob, cfg.signal_k, rng, cfg.signal_two_sided)

    # --- volatility path ------------------------------------------------------------
    regime = np.zeros(n, dtype=int)
    sigma_bar = np.full(n, sig_d)
    if cfg.vol_model == "markov":
        regime = _markov_regimes(n, cfg.p_stay, rng)
        mult = np.array(cfg.vol_mult, dtype=float)
        if cfg.normalise_vol:
            # stationary distribution of the 2-state chain, then rescale so that the
            # *unconditional* variance equals sigma^2 -> the three vol_models are comparable
            p00, p11 = cfg.p_stay
            pi1 = (1.0 - p00) / ((1.0 - p00) + (1.0 - p11))
            pi = np.array([1.0 - pi1, pi1])
            mult = mult / np.sqrt(float(pi @ mult ** 2))
        sigma_bar = sig_d * mult[regime]
    elif cfg.vol_model == "garch":
        alpha, beta = cfg.garch
        omega = sig_d ** 2 * (1.0 - alpha - beta)
    elif cfg.vol_model != "none":
        raise ValueError(f"unknown vol_model {cfg.vol_model!r}")

    # --- intra-bar path -------------------------------------------------------------
    m = max(M, 1)
    dt = 1.0 / m
    zmat = rng.standard_normal((n, m))

    fine = np.empty((n, m + 1))
    level = np.log(cfg.s0)
    var_t = sig_d ** 2                                   # garch state
    for t in range(n):
        if cfg.vol_model == "garch":
            sigma_bar[t] = np.sqrt(var_t)
        s_t = sigma_bar[t]
        drift_t = mu_d + cfg.signal_drift * s_t * z[t]    # <- the planted edge

        inc = (drift_t - 0.5 * s_t ** 2) * dt + s_t * np.sqrt(dt) * zmat[t]
        path = level + np.concatenate(([0.0], np.cumsum(inc)))
        fine[t] = np.exp(path)
        ret_t = path[-1] - level
        level = path[-1]

        if cfg.vol_model == "garch":
            eps = ret_t - drift_t
            var_t = omega + alpha * eps ** 2 + beta * var_t

    # --- OHLC bars ------------------------------------------------------------------
    idx = pd.bdate_range(cfg.start, periods=n, name="date")
    bars = pd.DataFrame(
        {
            "open": fine[:, 0],
            "high": fine.max(axis=1),
            "low": fine.min(axis=1),
            "close": fine[:, -1],
        },
        index=idx,
    )
    # volume: plausible, correlated with vol — never used as ground truth
    bars["volume"] = (1e6 * (sigma_bar / sig_d) * np.exp(0.3 * rng.standard_normal(n))).round()

    # --- observable features --------------------------------------------------------
    feats = pd.DataFrame(index=idx)
    feats["x_signal"] = cfg.snr * z + _ar1(n, cfg.feat_noise_phi, rng)
    for j in range(cfg.n_noise_features):
        feats[f"x_noise{j}"] = _ar1(n, cfg.feat_noise_phi, rng)
    feats = feats.join(price_features(bars))

    truth = pd.DataFrame(
        {"z": z, "regime": regime, "sigma_bar": sigma_bar,
         "drift_bar": mu_d + cfg.signal_drift * sigma_bar * z},
        index=idx,
    )

    minute_idx = pd.DatetimeIndex(
        np.repeat(idx.values, m + 1)
        + np.tile(np.arange(m + 1) * np.timedelta64(1, "m"), n)
        + np.timedelta64(570, "m")            # 09:30 open
    )
    return SimData(cfg=cfg, bars=bars, fine=fine, fine_index=minute_idx,
                   features=feats, truth=truth)


def price_features(bars: pd.DataFrame) -> pd.DataFrame:
    """Ordinary price-derived features. Deliberately *serially correlated* — that
    persistence is what makes overlapping-label leakage exploitable in notebook 04."""
    c = bars["close"]
    lr = np.log(c).diff()
    out = pd.DataFrame(index=bars.index)
    out["mom_5"] = c.pct_change(5)
    out["mom_20"] = c.pct_change(20)
    out["vol_20"] = lr.rolling(20).std()
    out["rng_5"] = ((bars["high"] - bars["low"]) / c).rolling(5).mean()
    out["zscore_50"] = (c - c.rolling(50).mean()) / c.rolling(50).std()
    return out


# --------------------------------------------------------------------------------------
# diagnostics
# --------------------------------------------------------------------------------------
def acf(x: np.ndarray, nlags: int = 20) -> np.ndarray:
    """Sample autocorrelation, lags 1..nlags (biased/Bartlett-consistent estimator)."""
    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    x = x - x.mean()
    denom = np.dot(x, x)
    return np.array([np.dot(x[:-k], x[k:]) / denom for k in range(1, nlags + 1)])


def acf_ci(n: int, level: float = 0.95) -> float:
    """+/- band under the white-noise null (Bartlett)."""
    from scipy.stats import norm
    return norm.ppf(0.5 + level / 2) / np.sqrt(n)


def stylised_facts(bars: pd.DataFrame, nlags: int = 20) -> dict:
    from scipy.stats import jarque_bera, kurtosis, skew
    lr = np.log(bars["close"]).diff().dropna().values
    jb = jarque_bera(lr)
    return {
        "n": len(lr),
        "mean_ann": lr.mean() * TRADING_DAYS,
        "vol_ann": lr.std(ddof=1) * np.sqrt(TRADING_DAYS),
        "skew": float(skew(lr)),
        "excess_kurtosis": float(kurtosis(lr, fisher=True)),
        "jarque_bera_p": float(jb.pvalue),
        "acf_ret": acf(lr, nlags),
        "acf_abs": acf(np.abs(lr), nlags),
        "acf_sq": acf(lr ** 2, nlags),
        "acf_band": acf_ci(len(lr)),
    }
